### ISSUE TITLE
BUG : mod launcher throw java.util.NoSuchElementException: No value present

### ISSUE THREAD

**Issue by LangArthur** [FlowArg/FlowUpdater#17]
Hi ! First of all, I am not 100% it is a bug or just me.

**Describe the bug**
I am installing a minecraft 1.19.3 with forge (44.1.17) and optifine (1.19.3_HD_U_I2_pre5). The download is going well but as soon as I launch minecract, the forge modLauncher crash with a NoSuchElementException (see the logs below).

**To Reproduce**
```
        VanillaVersion version = new VanillaVersionBuilder().withName("1.19.3").build();
        UpdaterOptions options = new UpdaterOptionsBuilder().build();
        AbstractForgeVersion forgeVersion = new ForgeVersionBuilder(ForgeVersionBuilder.ForgeVersionType.NEW)
            .withForgeVersion("44.1.17")
            .withOptiFine(new OptiFineInfo("preview_OptiFine_1.19.3_HD_U_I2_pre5", true))
            .build();
        FlowUpdater updater = new FlowUpdaterBuilder()
            .withVanillaVersion(version)
            .withUpdaterOptions(options)
            .withModLoaderVersion(forgeVersion)
            .build()
```
2. wait for the download.
3. See error

**Expected behavior**
No exception.

**Logs**

Here is the few logs just before the exception.
```
[12:16:12] [main/INFO]: ModLauncher running: args [--username, MyUsername, --version, 1.19.3, --gameDir, path\to\my\folder, --assetsDir, path\to\my\folder\assets, --assetIndex, 1.19, --uuid, 3b855cd86d9f4552a06267bc38feb8fc, --accessToken, ????????, --userType, mojang, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 44.1.17, --fml.mcVersion, 1.19.3, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20221207.122022]
[12:16:12] [main/INFO]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.4 by Oracle Corporation; OS Windows 11 arch amd64 version 10.0
Exception in thread "main" java.util.NoSuchElementException: No value present
        at java.base/java.util.Optional.orElseThrow(Optional.java:377)
        at cpw.mods.modlauncher.LaunchServiceHandler.lambda$new$0(LaunchServiceHandler.java:39)
        at cpw.mods.modlauncher.util.ServiceLoaderUtils.streamServiceLoader(ServiceLoaderUtils.java:33)
        at cpw.mods.modlauncher.LaunchServiceHandler.<init>(LaunchServiceHandler.java:39)
        at cpw.mods.modlauncher.Launcher.<init>(Launcher.java:53)
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
```

I dig a bit into the full log to see if some step where failing ... I found the following but after some searching, I don't think it is related.
```
...
Forge Auto Renaming Tool v0.1.22
log: null
input: path\to\my\folder\libraries\net\minecraft\client\1.19.3-20221207.122022\client-1.19.3-20221207.122022-slim.jar       
output: path\to\my\folder\libraries\net\minecraft\client\1.19.3-20221207.122022\client-1.19.3-20221207.122022-srg.jar       
threads: 16
Names: path\to\my\folder\libraries\de\oceanlabs\mcp\mcp_config\1.19.3-20221207.122022\mcp_config-1.19.3-20221207.122022-mappings-merged.txt(reversed: false)
Fix Annotations: true
Fix Records: true
Fix Identifiers: ALL
Fix SourceFile: JAVA
Fix Line Numbers: false
Strip codesigning signatures: false
Adding Libraries to Inheritance
Reading Input:path\to\my\folder\libraries\net\minecraft\client\1.19.3-20221207.122022\client-1.19.3-20221207.122022-slim.jar
Adding input to inheritence map
Processing entries
Cant Find Class: com/google/common/collect/ImmutableMap$Builder
...
```
followed by a huge list of class not found.

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
I managed to make my launcher work with minecraft 1.16.5, but now with 1.19.3 it crashs. I am using java 17, might be a reason for the crash ?
Also, I installed forge and optifine manualy, launch them through the official minecraft launcher : everything is working.

**Comment by FlowArg** [comment]
Can you send the code that launches the game please ?

**Comment by LangArthur** [comment]
There it is : 

```
            gameType.setNFVD(new NewForgeVersionDiscriminator(path\to\my\folder, "1.19.3", "44.1.17));
            GameInfos infos = new GameInfos(
                "myServer",
                new GameVersion("1.19.3", GameType.V1_13_HIGHER_FORGE),
                new GameTweak[] {});
            ExternalLaunchProfile profile = MinecraftLauncher.createExternalProfile(infos, GameFolder.FLOW_UPDATER_1_19_SUP, m_authInfos);
            List<String> params = profile.getVmArgs();
            params.add(formatRamArgument(ramValue));
            profile.setVmArgs(params);
            ExternalLauncher launcher = new ExternalLauncher(profile);
    
            launcher.launch();
```

**Comment by FlowArg** [comment]
U should use NoFramework directly instead of using the old External Launcher.

**Comment by LangArthur** [comment]
Ok, I will try with it and come back if I need more assitance !
