### ISSUE TITLE
BUG : Fabric URL doesn't exist (UnknownHostException)

### ISSUE THREAD

**Issue by xii69** [FlowArg/FlowUpdater#19]
**Describe the bug**
When i try to download latest fabric version using `FabricVersionBuilder` it doesn't download the fabric file.

**To Reproduce**
1. Create a new kotlin project
2. Create new `FabricVersion` using `FabricVersionBuilder`
```kotlin
val builder = FabricVersionBuilder()
    .withFabricVersion("0.14.22")
    .build()
```
3. Create new `FlowUpdater` using `FlowUpdaterBuilder`
```kotlin
val updater = FlowUpdater.FlowUpdaterBuilder()
    .withModLoaderVersion(builder)
    .build()
```
4. Use `FlowUpdater#update`
5. See error
```
5:27:56 PM: Executing 'run'...

> Task :processResources NO-SOURCE
> Task :prepareAppResources NO-SOURCE
> Task :compileKotlin
> Task :compileJava NO-SOURCE
> Task :classes UP-TO-DATE
> Task :jar

> Task :run
[05:28:00] [FlowUpdater] [INFO]: ------------------------- FlowUpdater for Minecraft no v1.8.1 -------------------------
[05:28:00] [FlowUpdater] [INFO]: Default callback will be used.
[05:28:00] [FlowUpdater] [INFO]: Checking library files...
[05:28:00] [FlowUpdater] [INFO]: Checking assets...
[05:28:00] [FlowUpdater] [INFO]: All vanilla files were successfully downloaded!
[05:28:00] [FlowUpdater] [INFO]: Installing Fabric, version: 0.14.22...
[05:28:00] [FlowUpdater] [INFO]: Downloading fabric installer...
[05:28:01] [FlowUpdater] [INFO]: Launching fabric installer...
Loading Fabric Installer: 0.11.2
Installing no with fabric 0.14.22
service FabricService{meta='https://meta.fabricmc.net/', maven='https://maven.fabricmc.net/'} failed: java.io.IOException: HTTP request to https://meta.fabricmc.net/v2/versions/loader/no/0.14.22/profile/json failed: 400
service FabricService{meta='https://meta2.fabricmc.net/', maven='https://maven2.fabricmc.net/'} failed: java.io.IOException: HTTP request to https://meta2.fabricmc.net/v2/versions/loader/no/0.14.22/profile/json failed: 400
service FabricService{meta='https://meta3.fabricmc.net/', maven='https://maven3.fabricmc.net/'} failed: java.net.UnknownHostException: meta3.fabricmc.net
[05:28:03] [FlowUpdater] [INFO]: Exception in thread "main" java.lang.RuntimeException: Failed to install Client
[05:28:03] [FlowUpdater] [INFO]: 	at net.fabricmc.installer.Main.main(Main.java:89)
[05:28:03] [FlowUpdater] [INFO]: Caused by: java.io.IOException: HTTP request to https://meta.fabricmc.net/v2/versions/loader/no/0.14.22/profile/json failed: 400
[05:28:03] [FlowUpdater] [INFO]: 	at net.fabricmc.installer.util.Utils.openUrl(Utils.java:148)
[05:28:03] [FlowUpdater] [INFO]: 	at net.fabricmc.installer.util.Utils.readString(Utils.java:90)
[05:28:03] [FlowUpdater] [INFO]: 	at net.fabricmc.installer.util.FabricService.lambda$queryMetaJson$0(FabricService.java:36)
[05:28:03] [FlowUpdater] [INFO]: 	at net.fabricmc.installer.util.FabricService.invokeWithFallbacks(FabricService.java:79)
[05:28:03] [FlowUpdater] [INFO]: 	at net.fabricmc.installer.util.FabricService.queryMetaJson(FabricService.java:36)
[05:28:03] [FlowUpdater] [INFO]: 	at net.fabricmc.installer.client.ClientInstaller.install(ClientInstaller.java:60)
[05:28:03] [FlowUpdater] [INFO]: 	at net.fabricmc.installer.client.ClientHandler.installCli(ClientHandler.java:181)
[05:28:03] [FlowUpdater] [INFO]: 	at net.fabricmc.installer.Main.main(Main.java:87)
[05:28:03] [FlowUpdater] [INFO]: 	Suppressed: java.io.IOException: HTTP request to https://meta2.fabricmc.net/v2/versions/loader/no/0.14.22/profile/json failed: 400
[05:28:03] [FlowUpdater] [INFO]: 		... 8 more
[05:28:03] [FlowUpdater] [INFO]: 	Suppressed: java.net.UnknownHostException: meta3.fabricmc.net
[05:28:03] [FlowUpdater] [INFO]: 		at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:572)
[05:28:03] [FlowUpdater] [INFO]: 		at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
[05:28:03] [FlowUpdater] [INFO]: 		at java.base/java.net.Socket.connect(Socket.java:633)
[05:28:03] [FlowUpdater] [INFO]: 		at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
[05:28:03] [FlowUpdater] [INFO]: 		at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
[05:28:03] [FlowUpdater] [INFO]: 		at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:533)
[05:28:03] [FlowUpdater] [INFO]: 		at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:638)
[05:28:03] [FlowUpdater] [INFO]: 		at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
[05:28:03] [FlowUpdater] [INFO]: 		at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
[05:28:03] [FlowUpdater] [INFO]: 		at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)
[05:28:03] [FlowUpdater] [INFO]: 		at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
[05:28:03] [FlowUpdater] [INFO]: 		at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
[05:28:03] [FlowUpdater] [INFO]: 		at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
[05:28:03] [FlowUpdater] [INFO]: 		at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:142)
[05:28:03] [FlowUpdater] [INFO]: 		at net.fabricmc.installer.util.Utils.openUrl(Utils.java:145)
[05:28:03] [FlowUpdater] [INFO]: 		... 7 more
[05:28:03] [FlowUpdater] [ERROR]: An error occurred : java.nio.file.NoSuchFileException: C:\Users\xii69\AppData\Roaming\.nlmc\.flowupdater\tempfabric\versions\fabric-loader-0.14.22-no\fabric-loader-0.14.22-no.json
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:236)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:432)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:422)
	at java.base/java.nio.file.Files.newInputStream(Files.java:160)
	at java.base/java.nio.file.Files.newBufferedReader(Files.java:2922)
	at java.base/java.nio.file.Files.readAllLines(Files.java:3412)
	at fr.flowarg.flowupdater.versions.FabricBasedVersion.parseAndMoveJson(FabricBasedVersion.java:42)
	at fr.flowarg.flowupdater.versions.FabricVersion.install(FabricVersion.java:125)
	at fr.flowarg.flowupdater.FlowUpdater.installModLoader(FlowUpdater.java:221)
	at fr.flowarg.flowupdater.FlowUpdater.installModLoader(FlowUpdater.java:212)
	at fr.flowarg.flowupdater.FlowUpdater.updateMinecraft(FlowUpdater.java:147)
	at fr.flowarg.flowupdater.FlowUpdater.update(FlowUpdater.java:126)
	at Minecraft$download$1.invokeSuspend(Minecraft.kt:20)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```
> Highlight:
service FabricService{meta='https://meta3.fabricmc.net/', maven='https://maven3.fabricmc.net/'} failed: java.net.UnknownHostException: meta3.fabricmc.net
[05:28:03] [FlowUpdater] [INFO]: Exception in thread "main" java.lang.RuntimeException: Failed to install Client

**Desktop:**
 - OS and Version:
![image](https://github.com/FlowArg/FlowUpdater/assets/87283583/f1daf1fe-c71d-4539-b38f-d2309f2ac867)

**Additional context**
Full code:
```kotlin
CoroutineScope(Dispatchers.Default).launch {
    val builder = FabricVersionBuilder()
        .withFabricVersion("0.14.22")
        .build()
    val updater = FlowUpdater.FlowUpdaterBuilder()
        .withModLoaderVersion(builder)
        .build()
    updater.update(GameDirGenerator.createGameDir("nlmc", true))
}
```

Game folder content (`C:\Users\<user>\AppData\Roaming\.nlmc`):
```
C:.
+---.flowupdater
|   |   fabric-installer-0.11.2.jar
|   |
|   \---tempfabric
|       \---versions
|           \---fabric-loader-0.14.22-no
|                   fabric-loader-0.14.22-no.jar
|
+---assets
+---libraries
\---natives
```

**Comment by FlowArg** [comment]
Hello, I have found the solution of this problem:
You must add to your code:
```kotlin
val vanillaVersion = new VanillaVersionBuilder()
        .withName("1.20.1")
        .build();
```
And then `.withVanillaVersion(vanillaVersion)` (in `FlowUpdaterBuilder`).

I didn't think at all that this error thrown by the Fabric installer would be caused because Minecraft Vanilla wasn't installed before :joy:!

Tell me if you still have issues with the Fabric installation process ;)

**Comment by xii69** [comment]
Problem solved, thank you. 👍
